# Generated by Django 5.0.4 on 2025-02-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='ecommerceuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
