# Generated by Django 5.0.4 on 2025-06-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
