# Generated by Django 5.0.4 on 2025-03-12 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='membre',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='membre',
            name='first_name',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='membre',
            name='last_name',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='membre',
            name='maison_non_loin_de',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membre',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membre',
            name='prefecture',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membre',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membre',
            name='sexe',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='membre',
            name='telephone',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='membre',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'Président'), ('VICE_PRESIDENT', 'Vice-Président'), ('SECRETAIRE', 'Secrétaire'), ('TRESORIER', 'Trésorier')], max_length=50),
        ),
    ]
