# Generated by Django 5.0.4 on 2025-04-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_remove_membre_utilisateur_membre_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationuser',
            name='nompop',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
