# Generated by Django 5.0.4 on 2025-04-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_associationuser_nompop'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rejet_motif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
