# Generated by Django 5.0.4 on 2025-04-08 09:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(default=2025)),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, 'Premier semestre'), (2, 'Deuxième semestre')], default=1)),
                ('total_cotisation', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_penalite', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_sanctions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nombre_filleuls_semestre', models.IntegerField(default=0)),
                ('interets', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('depenses_lucratives', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dividendes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('assistance_joie_obtenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('assistance_joie_reste', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=10)),
                ('assistance_detresse_obtenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('assistance_detresse_reste', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=10)),
                ('montant_total_pret_accorde', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('montant_total_assistance_accordee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('assistance_accorde', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pret_accorde', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('part_sociale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('part_lucrative', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_sociale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_lucrative', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carnets', to='parti.partiuser')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cotisation', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('penalite', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sanctions', models.TextField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='parti.carnet')),
            ],
        ),
    ]
