# Generated by Django 5.0.4 on 2025-04-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parti', '0002_carnet_lignecotisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partiuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
