# Generated by Django 5.0.4 on 2026-05-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parti', '0003_alter_partiuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='annee',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
