# Generated by Django 5.0.4 on 2025-03-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_donateur',
            field=models.BooleanField(default=False),
        ),
    ]
