# Generated by Django 5.0.4 on 2025-04-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_is_donateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nompop',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
