# Generated by Django 5.0.4 on 2025-04-18 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_nompop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField()),
                ('numero', models.CharField(max_length=20)),
                ('operateur', models.CharField(choices=[('T-MONEY', 'TMoney'), ('FLOOZ', 'Flooz')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SUCCES', 'Succès'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
