"""
Django settings for creationjames project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from django.utils.translation import gettext_lazy as _
import paypalrestsdk

from dotenv import load_dotenv

load_dotenv()
paypalrestsdk.configure({
    "mode": "sandbox",  # "sandbox" ou "live"
    "client_id": os.getenv('client_id'),
    "client_secret": os.getenv('client_secret')
})
LANGUAGES = [
    ('en', _('English')),
    ('fr', _('French')),
    ('es', _('Spanish')),
    # Ajoutez d'autres langues selon vos besoins
]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sri_+j-(lnm#wn-(&qh@m+cwmb*#a3v4ol%c39w%hvwptc8fqr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# settings.py

# ALLOWED_HOSTS = [
#     'localhost',  # pour le développement local
#     '127.0.0.1',  # pour le développement local
#     'de46-2c0f-f0f8-89b-5e00-f105-a04e-e4a-6a71.ngrok-free.app', 
#      "82.29.170.21",
#     'creationjames.com',
#     'www.creationjames.com'
# ]

ALLOWED_HOSTS = ['192.168.137.1', 'localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    'https://de46-2c0f-f0f8-89b-5e00-f105-a04e-e4a-6a71.ngrok-free.app',  # Remplacez par votre lien Ngrok
    'http://creationjames.com',  
    'https://creationjames.com',  
    'https://www.creationjames.com',  
]

CORS_ALLOWED_ORIGINS = [
    'https://de46-2c0f-f0f8-89b-5e00-f105-a04e-e4a-6a71.ngrok-free.app',  # Remplacez par votre lien Ngrok
    'http://creationjames.com',  
    'https://creationjames.com',  
    'https://www.creationjames.com',  
]


#ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

DEFAULT_USER_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'blog',
    'homepage',
    'ecommerce',
    'authentication',
    'user_avatar',
    'mathfilters',
    'association',
    'parti',
    'notifications',
    'phonenumber_field',
    'django_select2',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.LanguageMiddleware',

]

ROOT_URLCONF = 'creationjames.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'creationjames.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', '82.29.170.21'),  # Utilisez 'db' pour Docker
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL de connexion et de redirection
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
AUTH_USER_MODEL = 'authentication.CustomUser'
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')

SUPER_USER_ID = 1
AUTHENTICATION_BACKENDS = [

    'authentication.backends.UsernameBackend',
    'parti.backends.EmailBackend',
    'ecommerce.backends.UsernameBackend',  #  l'application 'ecommerce'
    'association.backends.NomBackend',  #  l'application 'association'
    'association.backends.IdentifiantBackend',  #  l'application 'association'
    'django.contrib.auth.backends.ModelBackend',  # Backend Django classique (si vous utilisez aussi le modèle `User` standard de Django)
]


CURRENCY_MAP = {
    'Côte d\'Ivoire': 'CFA',
    'France': 'EUR',
    'États-Unis': 'USD',
    # Ajoutez d'autres pays et devises ici
}
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') # Remplacez par votre mot de passe
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Stockage en base de données
SESSION_COOKIE_AGE = 3600  # 1 heure
SESSION_COOKIE_SECURE = False  # Désactiver en local si HTTPS n'est pas utilisé
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_NAME = "sessionid"  # Vérifie qu'il est bien nommé
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'


TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER')
# settings.py
CINETPAY_API_KEY = os.getenv('CINETPAY_API_KEY')
CINETPAY_SITE_ID = os.getenv('CINETPAY_SITE_ID')
CINETPAY_SECRET_KEY = os.getenv('CINETPAY_SECRET_KEY') # Secret Key
CINETPAY_BASE_URL = os.getenv('CINETPAY_BASE_URL')  # URL de l'API CinetPay
WHATSAPP_NUMBER = os.getenv("WHATSAPP_NUMBER")

